#!/usr/bin/env bash

if [[ -r vendor/install ]]; then
  export PATH="$(pwd)/vendor/install/bin:$PATH"
  export CPATH="$(pwd)/vendor/install/include:$CPATH"
  export CPATH="$(pwd)/vendor/install/include/libelf:$CPATH"
  export LIBRARY_PATH="$(pwd)/vendor/install/lib:$LIBRARY_PATH"
  export LD_LIBRARY_PATH="$(pwd)/vendor/install/lib:$LD_LIBRARY_PATH"
  export PKG_CONFIG_PATH="$(pwd)/vendor/install/lib/pkgconfig:$PKG_CONFIG_PATH"
fi

./waf-bin $@

