#!/usr/bin/env bash
## Stamp an ELF file with OGRT signature
set -euo pipefail

file=${1:-}

STAMP_ASSEMBLY=$(mktemp)

STAMP_VERSION="0x01"
UUID=$(uuidgen -r)

/bin/cat <<EOA > $STAMP_ASSEMBLY
    .section ".note.ogrt.info", "a"
    .p2align 2
    .long 1f - 0f           # name size (not including padding)
    .long 3f - 2f           # desc size (not including padding)
    .long 0x4F475254        # type
0:  .asciz "OGRT"           # name
1:  .p2align 2
2:  .byte  ${STAMP_VERSION} # version
    .asciz "${UUID}"        # uuid
3:  .p2align 2
EOA

echo "wrote assembly file '${STAMP_ASSEMBLY}' with OGRT signature (${UUID})."

